# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import currency_rates_pb2 as currency__rates__pb2


class ExchangeRateServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.subscribe = channel.unary_stream(
        '/ExchangeRateService/subscribe',
        request_serializer=currency__rates__pb2.Subscription.SerializeToString,
        response_deserializer=currency__rates__pb2.RatesUpdate.FromString,
        )


class ExchangeRateServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def subscribe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ExchangeRateServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.subscribe,
          request_deserializer=currency__rates__pb2.Subscription.FromString,
          response_serializer=currency__rates__pb2.RatesUpdate.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ExchangeRateService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
